### ISSUE TITLE
valid AST? Escodegen with markdown-to-ast

### ISSUE THREAD

**Issue by sholtomaud** [azu/markdown-to-ast#10]
I've tried using escodegen to parse the AST output from markdown-to-ast, but it fails.

Is markdown-to-ast valid AST?

**Comment by azu** [comment]
markdown-to-ast is a implementation of [TxtAST](https://github.com/textlint/textlint/blob/master/docs/txtnode.md) and [Unist](https://github.com/wooorm/unist).
It is not JavaScript AST well-known as [ESTree](https://github.com/estree/estree).
[escodegen](https://github.com/estools/escodegen) could only treat JavaScript AST.

> I've tried using escodegen to parse the AST output from markdown-to-ast, but it fails.

So, It it expected behavitor.

FYI: If you want to get Markdown parser/generator, use directly https://github.com/wooorm/remark.

**Comment by sholtomaud** [comment]
Ah ok. Thanks for the explanation.
