### ISSUE TITLE
Update remark

### ISSUE THREAD

**Issue by wooorm** [azu/markdown-to-ast#14]
Hi! :wave:

I think it’s time to update to a newer remark! There were quite some [fixes since `^5.0.1`](https://github.com/wooorm/remark/releases).

Let me know if you need help!

**Comment by azu** [comment]
Yes! I will update this in next week.

TBD: I plan that move this module into monorepo for integration test.
https://github.com/textlint/textlint/issues/270

**Comment by wooorm** [comment]
Yay! 🎉
