### ISSUE TITLE
missing type mapping for table.

### ISSUE THREAD

**Issue by Jxck** [azu/markdown-to-ast#7]
`Table`, `TableCell`, `TableRow` type mappings are missing.

in https://github.com/textlint/markdown-to-ast/blob/master/lib/markdown/mapping/markdown-syntax-map.js

**Comment by azu** [comment]
We'll check it lator.
- [x] Research other makup language
- [x] Stability of `Table`/`TableHeader`/`TableCell`/`TableRow`
  - Where is `TableBody` ?
